Add Business Service
calvinkmts/expert-pancake pull request #1
Opened 2022-11-20 09:55 UTC by verrellg97

2022-11-20 10:06 UTC, calvinkmts commented
itu semua .DS_store files nya tolong dihapus jangan dimasukin ke repository

2022-11-20 10:07 UTC, calvinkmts commented
itu kenapa ada token di service business? dipake dimana?

2022-11-20 10:23 UTC, calvinkmts requested changes

2022-11-20 10:23 UTC, calvinkmts commented on service/business/model/service.go
> +	HelloWorld(w http.ResponseWriter, r *http.Request) error
hapus

2022-11-20 10:23 UTC, calvinkmts commented on service/business/model/service.go
> +	HelloError(w http.ResponseWriter, r *http.Request) error
hapus kalau ga dipake, yang di account ada buat poc

2022-11-20 10:23 UTC, calvinkmts commented on service/business/util/password.go
> +import (
buat apa ya ini?

2022-11-20 10:23 UTC, calvinkmts commented on service/business/model/const.go
> +const ()
kalau gaada isinya hapus file nya.

2022-11-20 10:23 UTC, calvinkmts commented on service/business/impl/service.go
> +	tokenMaker token.Maker
token dipake dimana?

2022-11-20 10:23 UTC, calvinkmts commented on service/business/impl/helloWorld.go
> +package impl
hapus file nya

2022-11-20 10:23 UTC, calvinkmts commented on service/business/impl/helloError.go
> +package impl
hapus file nya

2022-11-20 10:23 UTC, calvinkmts commented on service/business/impl/getUserCompanies.go
> +	var keyword = "%"
ini apa?

2022-11-20 10:23 UTC, calvinkmts commented on service/business/config/business.json
> +  "token": {
kepake?

2022-11-20 10:23 UTC, calvinkmts commented on service/business/impl/getUserCompanies.go
> +		keyword = keyword + req.Keyword + "%"
kalau mau bikin wildcard ditaruh di tempatnya yang berhubungan.. kecuali ada alasan yang better dipisah.

2022-11-20 10:23 UTC, calvinkmts commented on service/business/impl/getUserCompanyBranches.go
> +	var keyword = "%"
ini sama

2022-11-20 10:23 UTC, calvinkmts commented on service/business/impl/updateCompany.go
> +		panic(err)
ini kalau dipanic service nya stop.. why?

2022-11-20 10:23 UTC, calvinkmts commented on service/business/db/transaction/createNewCompanyBranchTrx.go
> +		companyBranchRes, err := q.UpsertCompanyBranch(ctx, db.UpsertCompanyBranchParams{
ini cuma masukin ke 1 table, perlu transaction?

2022-11-20 10:23 UTC, calvinkmts commented on service/business/db/transaction/createNewCompanyTrx.go
> +func (trx *Trx) CreateNewCompanyTrx(ctx context.Context, arg CreateNewCompanyTrxParams) (CreateNewCompanyTrxResult, error) {
1 table perlu transaction?

2022-11-20 10:26 UTC, calvinkmts commented
Makefile, docker-compose file nya belum ditambahin tuh

2022-11-21 04:59 UTC, calvinkmts requested changes

2022-11-21 04:59 UTC, calvinkmts commented on Makefile
> +build_business:
build_business nya belum ditambahin di `make up_build`

jadinya 
`up_build: build_account build_business`

2022-11-21 04:59 UTC, calvinkmts commented on docker-compose.yml
> +      - "5000:5000"
kasih aja port nya 4010, port yang dipake di service nya kasih 4000 gpp kan sudah jalan di docker container sdah ke isolasi.. yang expose nya yang dibedain... gausah terlalu besar, cepet habis nanti

2022-11-21 04:59 UTC, calvinkmts commented on service/business/config/business.json
> +    "port": "5000"
ini server port nya sama reasonsnya kek yg di bagian docker-compose nya

2022-11-21 08:40 UTC, verrellg97 commented on Makefile
> +build_business:
Ok sorry kelewatan baca kalau ada up_build itu

2022-11-21 09:51 UTC, calvinkmts requested changes

2022-11-21 09:51 UTC, calvinkmts commented on service/business/config/business.json
> +    "port": "40010"
4010?

2022-11-22 04:15 UTC, calvinkmts approved these changes

2022-11-22 04:18 UTC, merged