feat(service inventory) update endpoint get warehouse
calvinkmts/expert-pancake pull request #107
Opened 2023-02-03 06:52 UTC by verrellg97

2023-02-03 09:43 UTC, calvinkmts requested changes

2023-02-03 09:43 UTC, calvinkmts commented on service/warehouse/impl/getWarehouses.go
> +		switch *req.Id {
kalau pake pointer bisa dibadingin dengan nil

2023-02-03 09:46 UTC, verrellg97 commented on service/warehouse/impl/getWarehouses.go
> +		switch *req.Id {
maksudnya langsung pake di switch case? gk perlu if?

2023-02-03 10:12 UTC, calvinkmts commented on service/warehouse/impl/getWarehouses.go
> +		switch *req.Id {
harusnya kalau udah pake pointer buat apa expect untuk ada string kosong ("") lagi... kan harusnya kirim yang ada isinya (?) kalau kosong biarin nil... sisanya brati ada isinya biar engga nested decision makingnya... 

paling dipastiin dulu kalau untuk field struct yang pointer kalau dikasih empty string balikannya apa.... dia bakal nil atau ada empty string nya kalau... kalau misal pun ada mending dibikin 1 level decision branching nya.

2023-02-03 10:23 UTC, verrellg97 commented on service/warehouse/impl/getWarehouses.go
> +		switch *req.Id {
ok

2023-02-04 06:01 UTC, calvinkmts approved these changes

2023-02-04 06:01 UTC, merged