feat (warehouse service) new endpoint get racks
calvinkmts/expert-pancake pull request #86
Opened 2023-01-28 08:59 UTC by widimicko

2023-01-28 09:40 UTC, calvinkmts requested changes

2023-01-28 09:40 UTC, calvinkmts commented on service/warehouse/impl/getRacks.go
> +	if req.Mode == "all" {
Ini kenapa pake ada mode all gini ya? Kenapa ga default nya ambil semua trus di bikin filter buat ngambil yang sesuai filter ya?

2023-01-28 09:40 UTC, calvinkmts commented on service/warehouse/db/query.sql
> +SELECT a.id, a.branch_id, a.name
Ini better dibikin pake filter" gitu aja sepertinya.. Aku lebih banyak liat kalau awalnya itu ambil semua baru setelah itu untuk ngambil beberapa pake filter... Contoh sqlc

https://github.com/kyleconroy/sqlc/discussions/364

2023-01-28 09:44 UTC, widimicko commented
![](https://github.trello.services/images/mini-trello-icon.png) [new endpoint - get racks](https://trello.com/c/Qq1c7gRS/105-new-endpoint-get-racks)

2023-01-28 10:45 UTC, calvinkmts requested changes

2023-01-28 10:45 UTC, calvinkmts commented on service/warehouse/impl/getRacks.go
> +	if req.Mode == "all" {
`if req.Mode == "all" { ... }`

ini aku jadi kepikiran mode nya bakal lebih dari 2 kah? kalau cuma dua ini dibikin jadi boolean aja.. itu satunya all satunya apa gitu.

2023-01-28 10:46 UTC, widimicko commented on service/warehouse/impl/getRacks.go
> +	if req.Mode == "all" {
Saat ini cuman bakal ada 2 mode mas

2023-01-28 11:14 UTC, calvinkmts requested changes

2023-01-28 11:14 UTC, calvinkmts commented on service/warehouse/model/service.go
> +	Mode     string `json:"mode" validate:"required"`
ini mode nya hanya all n available? 

```
type GetRacksRequest struct {
	BranchId          string `json:"branch_id" validate:"required"`
	Keyword          string `json:"keyword"`
	IsGetAvailable string `json:"is_get_available" // ini kalau ga dikirim nanti jadi false
}
```

2023-01-28 11:14 UTC, calvinkmts commented on service/warehouse/db/query.sql
> +        @is_get_all::bool THEN TRUE ELSE b.rack_id IS NULL END;
`@is_get_all::bool THEN TRUE ELSE b.rack_id IS NULL END;`

jadi

`@is_get_available::bool THEN b.rack_id IS NULL ELSE TRUE END;`

2023-01-28 11:14 UTC, calvinkmts commented on service/warehouse/impl/getRacks.go
> +	if req.Mode == "available" {
ini kedepannya kalau ada if else if else yang cuma 1 statement pake switch statement...

2023-01-28 11:14 UTC, calvinkmts commented on service/warehouse/impl/getRacks.go
> +		IsGetAll: is_get_all,
ini kalau pake model yang kutulis harusnya bisa langsung tanpa if" lagi diatasnya, harusnya jadi lebih ramping isinya.

2023-01-28 11:24 UTC, widimicko commented on service/warehouse/impl/getRacks.go
> +		IsGetAll: is_get_all,
Oke mas, otw push

2023-01-28 11:30 UTC, widimicko commented on service/warehouse/model/service.go
> +	Mode     string `json:"mode" validate:"required"`
Ini tk buat boolean kok ndk bisa ya mas? Di docs nya ada padahal

2023-01-28 11:31 UTC, widimicko commented on service/warehouse/impl/getRacks.go
> +		IsGetAll: is_get_all,
Ini kalau requestna ndk bisa diganti boolean, hrus pake conditiom berarti mas

2023-01-30 04:09 UTC, calvinkmts approved these changes

2023-01-30 04:17 UTC, merged